language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt install -y gdal-bin python3-gdal
  - dpkg-query -L python3-gdal
env:
  - LD_LIBRARY_PATH=/usr/lib:/usr/lib/python3/dist-packages/osgeo PYTHONPATH=/usr/lib/python3/dist-packages
install:
  - pip install ./python/skope_analysis/
script: pytest -v


